version: "3.9"

networks:
    rede_byd:
        external: true

services:
  app_auto:
    restart: always
    build: ./app_auto/.
    container_name: app_auto
    image: app_auto
    volumes:
      - ./data:/app/data
      - ./output_auto:/app/output_folder
      - ./images_folder:/app/images_folder
    networks:
      - rede_byd
    ports:
      - "8501:8501"

  app_manual:
    restart: always
    build: ./app_manual/.
    container_name: app_manual
    image: app_manual
    volumes:
      - ./data:/app/data
      - ./output_manual:/app/output_folder
      - ./images_folder:/app/images_folder
    networks:
      - rede_byd
    ports:
      - "8503:8503"

  # streamlit_app:
  #   restart: always
  #   build: ./streamlit/.
  #   container_name: streamlit_app
  #   image: streamlit_app
  #   volumes:
  #     - ./data:/app/data
  #     - ./output_auto:/app/output_folder
  #     - ./images_folder:/app/images_folder
  #   networks:
  #     - rede_byd
  #   ports:
  #     - "8501:8501"

  streamlit_config:
    restart: always
    build: ./config/.
    container_name: streamlit_config
    image: streamlit_config
    volumes:
      - ./data:/app/data
    networks:
      - rede_byd
    ports:
      - "8502:8502"

  segment_cell:
    restart: always
    build: ./models/segment_cell/.
    container_name: segment_cell
    image: segment_cell
    networks:
      - rede_byd
    ports:
      - "3000:3000"

  detection_model:
    restart: always
    build: ./models/detection_model/.
    privileged: true
    container_name: detection_model
    image: detection_model
    networks:
      - rede_byd
    ports:
      - "6000:6000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  segmentation_model:
    restart: always
    build: ./models/segmentation_model/.
    privileged: true
    container_name: segmentation_model
    image: segmentation_model
    networks:
      - rede_byd
    ports:
      - "4000:4000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vit_model:
    restart: always
    build: ./models/vit_model/.
    privileged: true
    container_name: vit_model
    image: vit_model
    networks:
      - rede_byd
    ports:
      - "7000:7000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mysql:
    restart: always
    image: mysql/mysql-server:latest
    #build: ./db/.
    container_name: mysql
    volumes:
      - /home/mysql:/var/lib/mysql
      - ./create-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - rede_byd
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
